omoa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("post/", include("post.urls")),
    path("review/", include("review.urls")),
    path("", include("ranking.urls")),
]
urlpatterns += static(
    prefix= settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT,
)

post/urls.py
from django.urls import path
from post import views

app_name = "post"
urlpatterns = [
    path("ott/<str:ott>/", views.ott_view, name= "ott_view"),
    path("post_detail/<int:id>/", views.post_detail, name= "post_detail"),
    path("post_detail/<int:post_id>/like/", views.post_detail_like, name= "post_detail_like"),
    path("import/", views.importExcel, name= "importExcel"),
]

ranking/urls.py
from django.urls import path
from ranking import views

app_name = "ranking"
urlpatterns = [
    path("",views.omoa_home, name = "home"),
    path("ranking/",views.ranking_page, name = "ranking"),
]

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from user import views

app_name = "user"
urlpatterns = [
    path("login/", views.login_view, name = "login"),
    path("logout/", views.logout_view, name = "logout"),
    path("signup/", views.signup, name = "signup"),
    path("my_page/<int:id>/", views.my_page, name = "mypage"),
    path("my_page/<int:id>/follow/", views.user_follow, name = "userfollow"),
    path("my_page/<int:id>/mylike/", views.my_likelist, name= "mylike"),
    path("my_page/<int:id>/myreview/", views.my_reviewlist, name= "myreview"),
    path("my_page/<int:id>/myfollow/", views.my_followlist, name= "myfollow"),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ranking/models.py
from django.db import models

# Create your models here.
class Last_update(models.Model):
    last_date = models.DateField("날짜", auto_now_add=True)

class Netflix_movieRank(models.Model):
    content_rank = models.CharField("순위",max_length=5)
    content_name = models.CharField("작품제목",max_length=50)
    content_period = models.CharField("기간",max_length=10)
    content_img = models.CharField("이미지", blank=True)

class Netflix_tvRank(models.Model):
    content_rank = models.CharField("순위",max_length=5)
    content_name = models.CharField("작품제목",max_length=50)
    content_period = models.CharField("기간",max_length=10)
    content_img = models.CharField("이미지", blank=True)

class Amazon_movieRank(models.Model):
    content_rank = models.CharField("순위",max_length=5)
    content_name = models.CharField("작품제목",max_length=50)
    content_period = models.CharField("기간",max_length=10, blank=True)
    content_img = models.CharField("이미지", blank=True)

class Amazon_tvRank(models.Model):
    content_rank = models.CharField("순위",max_length=5)
    content_name = models.CharField("작품제목",max_length=50)
    content_period = models.CharField("기간",max_length=10, blank=True)
    content_img = models.CharField("이미지", blank=True)

class Disney_Rank(models.Model):
    content_rank = models.CharField("순위",max_length=5)
    content_name = models.CharField("작품제목",max_length=50)
    content_period = models.CharField("기간",max_length=10)
    content_img = models.CharField("이미지", blank=True)

class Wavve_movieRank(models.Model):
    content_rank = models.CharField("순위",max_length=5)
    content_name = models.CharField("작품제목",max_length=50)
    content_period = models.CharField("기간",max_length=10)
    content_img = models.CharField("이미지", blank=True)

class Wavve_tvRank(models.Model):
    content_rank = models.CharField("순위",max_length=5)
    content_name = models.CharField("작품제목",max_length=50)
    content_period = models.CharField("기간",max_length=10)
    content_img = models.CharField("이미지", blank=True)

ranking/views.py
from django.shortcuts import render, redirect
from ranking.models import Netflix_movieRank, Netflix_tvRank, Amazon_movieRank, Amazon_tvRank, Disney_Rank, Wavve_movieRank, Wavve_tvRank

# Create your views here.
def omoa_home(request):
    return redirect("ranking:ranking")
    

def ranking_page(request):

    netflix_movieranks = Netflix_movieRank.objects.all()
    netflix_tvranks = Netflix_tvRank.objects.all()
    amazon_movieranks = Amazon_movieRank.objects.all()
    amazon_tvranks = Amazon_tvRank.objects.all()
    disney_ranks = Disney_Rank.objects.all()
    wavve_movieranks = Wavve_movieRank.objects.all()
    wavve_tvranks = Wavve_tvRank.objects.all()

    context = {
        "netflix_movieranks": netflix_movieranks,
        "netflix_tvranks": netflix_tvranks,
        "amazon_movieranks": amazon_movieranks,
        "amazon_tvranks": amazon_tvranks,
        "disney_ranks": disney_ranks,
        "wavve_movieranks": wavve_movieranks,
        "wavve_tvranks": wavve_tvranks
    }

    return render(request,"ranking/ranking.html",context)

templates/ranking/ranking.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OMOA - Ranking</title>
    <link href="{% static 'css/style2.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'post:ott_view' ott='all' %}">OMOA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    {% if user.id %}
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'user:mypage' user.id %}">My Page</a></li>
                    {% endif %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">OTT</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Netflix' %}">Netflix</a></li>
                                <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Amazon' %}">Amazon</a></li>
                                <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Disney' %}">Disney</a></li>
                                <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='wavve' %}">wavve</a></li>
                            </ul>
                    </li>
                </ul>
                {% if user.id %}
                <form class="d-flex">
                    <a href="{% url 'user:logout' %}">Logout</a>
                </form>
                {% else %}
                <form class="d-flex">
                    <a href="{% url 'user:login' %}">Sign In</a>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
    <!-- Table Product -->
    <div class="row">
        <div class="col-12">
            <div class="card card-default">
                <div class="card-header">
                    <h2>Neflix Movie Top N</h2>
                    <div class="dropdown">
                        <!-- <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false"> Yearly Chart
                        </a> -->
                    </div>
                </div>
                <div class="card-body">
                    <table id="productsTable" class="table table-hover table-product" style="width:100%">
                        <tbody>
                            {% for nrank in netflix_movieranks %}
                            <tr>
                                <td style="width:5%; vertical-align: middle; text-align: center;">{{ nrank.content_rank }}</td>
                                <td class="py-0" style="width:10%">
                                    <img src="{{ nrank.content_img }}" alt="">
                                </td>
                                <td style="vertical-align: middle;">{{ nrank.content_name }}</td>
                                <td style="width:5%; vertical-align: middle; text-align: center;">{{ nrank.content_period }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
                <div class="card-header">
                    <h2>Neflix Tv Top N</h2>
                    <div class="dropdown">
                    </div>
                </div>
                <div class="card-body">
                    <table id="productsTable" class="table table-hover table-product" style="width:100%">
                        <tbody>
                            {% for nrank in netflix_tvranks %}
                            <tr>
                                <td style="width:5%; vertical-align: middle; text-align: center;">{{ nrank.content_rank }}</td>
                                <td class="py-0" style="width:10%">
                                    <img src="{{ nrank.content_img }}" alt="">
                                </td>
                                <td style="vertical-align: middle;">{{ nrank.content_name }}</td>
                                <td style="width:5%; vertical-align: middle; text-align: center;">{{ nrank.content_period }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
            <div class="card card-default">
                <div class="card-header">
                    <h2>Amazon Movie Top N</h2>
                    <div class="dropdown">
                    </div>
                </div>
                <div class="card-body">
                    <table id="productsTable" class="table table-hover table-product" style="width:100%">
                        <tbody>
                            {% for arank in amazon_movieranks %}
                            <tr>
                                <td style="width:5%; vertical-align: middle; text-align: center;">{{ arank.content_rank }}</td>
                                <td class="py-0" style="width:10%">
                                    <img src="{{ arank.content_img }}" alt="">
                                </td>
                                <td style="vertical-align: center;">{{ arank.content_name }}</td>
                                <td style="width:5%; vertical-align: middle; text-align: center;">{{ arank.content_period }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
                <div class="card-header">
                    <h2>Amazon Tv Top N</h2>
                    <div class="dropdown">
                    </div>
                </div>
                <div class="card-body">
                    <table id="productsTable" class="table table-hover table-product" style="width:100%">
                        <tbody>
                            {% for arank in amazon_tvranks %}
                            <tr>
                                <td style="width:5%; vertical-align: middle; text-align: center;">{{ arank.content_rank }}</td>
                                <td class="py-0" style="width:10%">
                                    <img src="{{ arank.content_img }}" alt="">
                                </td>
                                <td style="vertical-align: middle;">{{ arank.content_name }}</td>
                                <td style="width:5%; vertical-align: middle; text-align: center;">{{ arank.content_period }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
            <div class="card card-default">
                <div class="card-header">
                    <h2>Disney Top N</h2>
                    <div class="dropdown">
                    </div>
                </div>
                <div class="card-body">
                    <table id="productsTable" class="table table-hover table-product" style="width:100%">
                        <tbody>
                            {% for drank in disney_ranks %}
                            <tr>
                                <td style="width:5%; vertical-align: middle; text-align: center;">{{ drank.content_rank }}</td>
                                <td class="py-0" style="width:10%">
                                    <img src="{{ drank.content_img }}" alt="">
                                </td>
                                <td style="vertical-align: middle; font-size: 20px;">{{ drank.content_name }}</td>
                                <td style="width:5%; vertical-align: middle; text-align: center;">{{ drank.content_period }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
            <div class="card card-default">
                <div class="card-header">
                    <h2>Wavve Movie Top N</h2>
                    <div class="dropdown">
                    </div>
                </div>
                <div class="card-body">
                    <table id="productsTable" class="table table-hover table-product" style="width:100%">
                        <tbody>
                            {% for wrank in wavve_movieranks %}
                            <tr>
                                <td style="width:5%; text-align: center; vertical-align: middle;">{{ wrank.content_rank }}</td>
                                <td class="py-0" style="width:10%">
                                    <img src="{{ wrank.content_img }}" alt="">
                                </td>
                                <td style="vertical-align: middle; font-size: 20px;">{{ wrank.content_name }}</td>
                                <td style="width:5%; text-align: center; vertical-align: middle;">{{ wrank.content_period }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-header">
                    <h2>Wavve Tv Top N</h2>
                    <div class="dropdown">
                    </div>
                </div>
                <div class="card-body">
                    <table id="productsTable" class="table table-hover table-product" style="width:100%">
                        <tbody>
                            {% for wrank in wavve_tvranks %}
                            <tr>
                                <td style="width:5%; text-align: center; vertical-align: middle;">{{ wrank.content_rank }}</td>
                                <td class="py-0" style="width:10%">
                                    <img src="{{ wrank.content_img }}" alt="">
                                </td>
                                <td style="vertical-align: middle; font-size: 20px;">{{ wrank.content_name }}</td>
                                <td style="width:5%; text-align: center; vertical-align: middle;">{{ wrank.content_period }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</body>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/listscripts.js"></script>

</html>