omoa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("post/", include("post.urls")),
    path("review/", include("review.urls")),
    path("", include("ranking.urls")),
]
urlpatterns += static(
    prefix= settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT,
)

post/urls.py
from django.urls import path
from post import views

app_name = "post"
urlpatterns = [
    path("ott/<str:ott>/", views.ott_view, name= "ott_view"),
    path("post_detail/<int:id>/", views.post_detail, name= "post_detail"),
    path("post_detail/<int:post_id>/like/", views.post_detail_like, name= "post_detail_like"),
    path("import/", views.importExcel, name= "importExcel"),
]

ranking/urls.py
from django.urls import path
from ranking import views

app_name = "ranking"
urlpatterns = [
    path("",views.omoa_home, name = "home"),
    path("ranking/",views.ranking_page, name = "ranking"),
]

review/urls.py
from django.urls import path
from review import views

app_name = "review"
urlpatterns = [
    path("",views.review_list, name = "review_list"),
    path("add/<int:post_id>/",views.review_add, name = "review_add"),
    path("delete/<int:review_id>/",views.review_delete, name = "review_delete"),
    path("<int:review_id>/",views.review_detail, name= "review_detail"),
    path("comment_add/", views.comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", views.comment_delete, name="comment_delete"),
]

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from user import views

app_name = "user"
urlpatterns = [
    path("login/", views.login_view, name = "login"),
    path("logout/", views.logout_view, name = "logout"),
    path("signup/", views.signup, name = "signup"),
    path("my_page/<int:id>/", views.my_page, name = "mypage"),
    path("my_page/<int:id>/follow/", views.user_follow, name = "userfollow"),
    path("my_page/<int:id>/mylike/", views.my_likelist, name= "mylike"),
    path("my_page/<int:id>/myreview/", views.my_reviewlist, name= "myreview"),
    path("my_page/<int:id>/myfollow/", views.my_followlist, name= "myfollow"),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey("user.User",
                             verbose_name = "작성자",
                             on_delete = models.CASCADE)
    post = models.ForeignKey("post.Post",
                             verbose_name="작품명",
                             on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add = True)
    title = models.CharField("제목")

    def __str__(self):
        return f"{self.user.id}의 게시글(id: {self.id})"
    

class Comment(models.Model):
    user = models.ForeignKey("user.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    review = models.ForeignKey("review.Review", verbose_name = "게시글", on_delete = models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add= True)

review/forms.py
from django import forms
from review.models import Review, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "review",
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs = {
                    "placeholder": "댓글 달기...",
                    "class":"form-control",
                    "rows":"3",
                    "style": "resize: none; width:90%; margin-right: 15px;",
                }
            )
        }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields =[
            "title",
            "content",
        ]
        widgets = {
            "title": forms.TextInput(
                attrs= {
                    "placeholder":"제목을 입력해주세요", "class":"form-control", "aria-describedby": "inputGroup-sizing-default", "style":"width:80%"
                }
            ),
            "content": forms.Textarea(
                attrs = {
                    "placeholder":"내용을 입력해주세요", "class":"form-control"
                }
            )
        }

review/views.py
from django.shortcuts import render, redirect
from review.models import Review, Comment
from post.models import Post
from review.forms import ReviewForm, CommentForm    
from django.views.decorators.http import require_POST
from django.http import HttpResponseForbidden
from django.db.models.query_utils import Q

# Create your views here.
def review_list(request):
    # 모든 글 목록을 템플릿으로 전달
    reviews = Review.objects.all()

    context = {
        "reviews": reviews,
        }
    return render(request,"review/review_list.html", context)

def review_add(request, post_id):
    post = Post.objects.get(pk=post_id)

    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit = False)
            review.user = request.user
            review.post_id = post_id    
            review.save()
            return redirect("review:review_list")
    else:
        form = ReviewForm()

    context = {
        "form":form,
        "post":post,
    }

    return render(request, 'review/review_add.html',context)

@require_POST
def review_delete(request, review_id):
    review = Review.objects.get(pk=review_id)
    print("리뷰삭제 실행, 대상 영화의 id: ",review.post.id)
    if review.user == request.user:
        review.delete()
        # return redirect("post:post_detail", review.post.id) 
        return redirect("review:review_list")
    
    else:
        return HttpResponseForbidden("이 리뷰를 삭제할 권한이 없습니다")

def review_detail(request,review_id):
    comment_form = CommentForm()
    

    review = Review.objects.get(pk=review_id)
    context = {
        "review":review,
        "comment_form":comment_form,
    }
    return render(request,"review/review_detail.html",context)

@require_POST
def comment_add(request):
    form = CommentForm(data = request.POST)

    print("commentadd!")
    
    if form.is_valid():
        # commit = False 옵션으로 메모리상에 Comment 객체 생성
        comment = form.save(commit = False)
        comment.user = request.user
        comment.save()

        return redirect("review:review_detail",comment.review.id)

    return redirect('review:review_list')
    
@require_POST
def comment_delete(request, comment_id):
    comment = Comment.objects.get(pk = comment_id)
    if comment.user == request.user:
        comment.delete()
        return redirect("review:review_detail",comment.review.id) 
    
    else:
        return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")

def review_list(request):
    if not request.user.is_authenticated: # 유저의 접근이 올바르지 않다면 로그인 화면으로 보내버리기
        return redirect("user:login")
    
    query = request.GET.get("q")

    if query:
        reviews = Review.objects.filter(Q(title__contains = query)|Q(post__content_name__contains = query))
    else:
        reviews = Review.objects.all()

    context = {
        "reviews": reviews,
        }
    return render(request,"review/review_list.html", context)

templates/review/review_add.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>OMOA</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles3.css' %}" rel="stylesheet" />

    <style>
        .background {
            background-image: url("{{ post.post_image }}");
            background-size: contain;
            background-repeat: no-repeat;
            background-position: center;
        }
    </style>
</head>

<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'post:ott_view' ott='all' %}">OMOA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'user:mypage' user.id %}">My Page</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">OTT</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Netflix' %}">Netflix</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Amazon' %}">Amazon</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Disney' %}">Disney</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='wavve' %}">wavve</a></li>
                        </ul>
                <li class="nav-item"><a class="nav-link"href="{% url 'review:review_list' %}">Review</a></li>
                </li>
            </ul>
            <form class="d-flex">
                <a href="{% url 'user:logout' %}">Logout</a>
            </form>
        </div>
    </div>
</nav>
<!-- Header-->
<header class="bg-dark py-5 background">
        <div class="container px-4 px-lg-5 my-5">
            <div class="display-4 fw-bolder">
                <a href="{% url 'post:post_detail' post.id %}" class="display-5 fw-bolder text-white mb-2">
                    {{ post.content_name }}
                </a>
                <p class="lead fw-normal text-white-50 mb-0">다양한 작품에 대해 의견을 남겨보세요 !</p>
            </div>
        </div>
    </div>
</div>
</div>
</header>
<div style="display: flex; justify-content: center; margin-top: 5%; margin-bottom: 5%;">
    <div class="card" style="width: 80%; height: 90%;">
        <div class="card-body">
            <h2 class="card-title" style="font-family: 'sans-serif';">리뷰 작성</h2>
            <form method="POST" action="{% url 'review:review_add' post.id %}">
                {% csrf_token %}
                <input type="hidden" name="post" value="{{ post.id }}">
                {{ form.as_p }}
                <button type="submit" class="btn btn-dark">Upload!</button>
            </form>
        </div>
    </div>
    </div>
    <!-- Footer-->
    <footer class="bg-dark">
        <div class="container px-5">
            <p class="m-0 text-center text-white">Copyright &copy; OMOA 2025</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>

templates/review/review_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>OMOA-{{ review.post.content_name}}의 Review</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon3.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/reviewstyles.css' %}" rel="stylesheet" />

<style>
    .background {
        background-image: url("{{ review.post.post_image }}"); 
        background-size: contain; 
        background-repeat: no-repeat; 
        background-position: center; 
}
</style>
<script>
    const netflixtext = ", Netflix Standard with Ads"
</script>
    </head>
    <body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'post:ott_view' ott='all' %}">OMOA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'user:mypage' user.id %}">My Page</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">OTT</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Netflix' %}">Netflix</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Amazon' %}">Amazon</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Disney' %}">Disney</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='wavve' %}">wavve</a></li>
                        </ul>
                <li class="nav-item"><a class="nav-link"href="{% url 'review:review_list' %}">Review</a></li>
                </li>
            </ul>
            <form class="d-flex">
                <a href="{% url 'user:logout' %}">Logout</a>
            </form>
        </div>
    </div>
</nav>
            <!-- Header-->
        <header class="bg-dark py-5 background">
                <div class="container px-4 px-lg-5 my-5">
                    <div class="display-4 fw-bolder">
                        <a href="{% url 'post:post_detail' review.post_id %}" class="display-5 fw-bolder text-white mb-2">
                            {{ review.post.content_name }}
                        </a>
                        <p class="lead fw-normal text-white-50 mb-0">다양한 작품에 대해 의견을 남겨보세요 !</p>
                    </div>
                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{ review.title }}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">{{ review.created }}</div>
                            <!-- Post categories-->
                            <a class="badge bg-secondary text-decoration-none link-light" href="{% url 'user:mypage' review.user.id %}">{{ review.user.username}} </a>
                            <a class="badge bg-secondary text-decoration-none link-light" href="{% url 'post:post_detail' review.post_id %}">{{review.post.content_name }}</a><!-- 리뷰 삭제 Form 추가 -->
                        {% if user == review.user %}
                        <form method="POST" action="{% url 'review:review_delete' review.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-danger" style="float: right;">삭제</button>
                        </form>
                        {% endif %}
                        </header>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">{{ review.content|linebreaks }}
                        </section>
                        
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <div class="post-comment-create">
                                    <form method="POST" action="{% url 'review:comment_add' %}" style="display: flex;">
                                        {% csrf_token %}
                                        <input type="hidden" name="review" value="{{ review.id }}">
                                        {{ comment_form.content }}
                                        <button class="btn btn-primary" type="submit" style="display: inline; margin-top: 20px; margin-bottom: 20px; width:100px;">작성</button>
                                    </form>
                                </div>
                                {% for comment in review.comment_set.all %}
                                <div class="d-flex" style="margin-top: 10px;">
                                    <a href="{% url 'user:mypage' comment.user.id %}"></a>
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="{{ comment.user.profile_image.url }}" width="45",height="30" /></div>
                                    <div class="ms-3 w-100">
                                        <a href="{% url 'user:mypage' comment.user.id %}">
                                        <div class="fw-bold">{{ comment.user.username }}</div>
                                        </a>
                                        {{ comment.content|linebreaks }}
                                        {{ comment.created }}{% if user == comment.user %}
                                        <form method="POST" action="{% url 'review:comment_delete' comment.id %}" class="text-end">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-outline-danger">
                                                삭제
                                            </button>
                                        </form>
                                        {% endif %}
                                    </div>
                                </div>
                                {% endfor%}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; OMOA</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/reviewscripts.js"></script>
    </body>
</html>

templates/review/review_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>OMOA-Review</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon2.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/liststyles.css' %}" rel="stylesheet" />
</head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'post:ott_view' ott='all' %}">OMOA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'user:mypage' user.id %}">My Page</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">OTT</a>
                              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                  <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Netflix' %}">Netflix</a></li>
                                  <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Amazon' %}">Amazon</a></li>
                                  <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Disney' %}">Disney</a></li>
                                  <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='wavve' %}">wavve</a></li>
                              </ul>
                        <li class="nav-item"><a class="nav-link"href="{% url 'review:review_list' %}">Review</a></li>
                        </li>
                    </ul>
                    <form class="d-flex" role="search" method="GET">
                        <input class="form-control me-2" type="search" placeholder="작품명,게시물 제목으로 검색" aria-label="Search" name="q" />
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">OMOA-Review List</h1>
                    <p class="lead fw-normal text-white-50 mb-0">다양한 작품에 대해 의견을 남겨보세요 !</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                  {% for review in reviews %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">{{ review.post.content_ott | cut:", Netflix Standard with Ads" }}</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ review.post.post_image }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ review.post.content_name }}</h5>
                                    <!-- Product price-->
                                    <span class="text-muted">{{ review.title }}-{{ review.user.username }}</span>
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'review:review_detail' review.id %}">click</a></div>
                            </div>
                        </div>
                    </div>
                  {% endfor %}
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; OMOA 2025</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/listscripts.js"></script>
    </body>
</html>