omoa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("post/", include("post.urls")),
    path("review/", include("review.urls")),
    path("", include("ranking.urls")),
]
urlpatterns += static(
    prefix= settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT,
)

post/urls.py
from django.urls import path
from post import views

app_name = "post"
urlpatterns = [
    path("ott/<str:ott>/", views.ott_view, name= "ott_view"),
    path("post_detail/<int:id>/", views.post_detail, name= "post_detail"),
    path("post_detail/<int:post_id>/like/", views.post_detail_like, name= "post_detail_like"),
    path("import/", views.importExcel, name= "importExcel"),
]

ranking/urls.py
from django.urls import path
from ranking import views

app_name = "ranking"
urlpatterns = [
    path("",views.omoa_home, name = "home"),
    path("ranking/",views.ranking_page, name = "ranking"),
]

review/urls.py
from django.urls import path
from review import views

app_name = "review"
urlpatterns = [
    path("",views.review_list, name = "review_list"),
    path("add/<int:post_id>/",views.review_add, name = "review_add"),
    path("delete/<int:review_id>/",views.review_delete, name = "review_delete"),
    path("<int:review_id>/",views.review_detail, name= "review_detail"),
    path("comment_add/", views.comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", views.comment_delete, name="comment_delete"),
]

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from user import views

app_name = "user"
urlpatterns = [
    path("login/", views.login_view, name = "login"),
    path("logout/", views.logout_view, name = "logout"),
    path("signup/", views.signup, name = "signup"),
    path("my_page/<int:id>/", views.my_page, name = "mypage"),
    path("my_page/<int:id>/follow/", views.user_follow, name = "userfollow"),
    path("my_page/<int:id>/mylike/", views.my_likelist, name= "mylike"),
    path("my_page/<int:id>/myreview/", views.my_reviewlist, name= "myreview"),
    path("my_page/<int:id>/myfollow/", views.my_followlist, name= "myfollow"),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    content_name = models.CharField("작품제목",max_length=50,blank=True, null=True)
    content_description = models.TextField("시놉시스",blank=True,null=True)
    content_act = models.CharField("출연진",blank=True,null=True)
    content_dir = models.CharField("감독",blank=True,null=True)
    content_ott = models.CharField("OTT", blank=True,null=True)
    content_genre = models.CharField("장르", blank=True,null=True)
    post_image = models.CharField("포스터", blank=True,null=True)
    content_year = models.CharField("개봉년도", max_length=4, blank=True,null=True)
    
    def __str__(self):
        return self.content_name

review/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey("user.User",
                             verbose_name = "작성자",
                             on_delete = models.CASCADE)
    post = models.ForeignKey("post.Post",
                             verbose_name="작품명",
                             on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add = True)
    title = models.CharField("제목")

    def __str__(self):
        return f"{self.user.id}의 게시글(id: {self.id})"
    

class Comment(models.Model):
    user = models.ForeignKey("user.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    review = models.ForeignKey("review.Review", verbose_name = "게시글", on_delete = models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add= True)

post/forms.py
from django import forms
from post.models import Post
from review.models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "user",
            "post",
            "content",
        ]
        

class PostForm(forms.Form):
    class meta:
        model = Post
        fields = '__all__'

post/views.py
from django.shortcuts import render, redirect
from django.db.models.query_utils import Q
from post.models import Post 
from review.forms import ReviewForm
from django.urls import reverse
from tablib import Dataset
from .xlimport import PostResource
# Create your views here.

def ott_view(request, ott):
    if not request.user.is_authenticated: # 유저의 접근이 올바르지 않다면 로그인 화면으로 보내버리기
        return redirect("user:login")

    print("ott_view 실행!")
    
    query = request.GET.get("q")
    print("query:", query)

    if ott == "all":
        search = Post.objects.all()
        if query:
            search = Post.objects.filter(content_name__contains = query)
    else:
        if query:
            search = Post.objects.filter(content_name__contains = query, content_ott__contains=ott)
        else:
            search = Post.objects.filter(content_ott__contains=ott)

    context = {
        "posts": search,
        "ott":ott,
    }

    return render(request,"post/post_list.html", context)

def post_detail(request, id):
    if not request.user.is_authenticated: # 유저의 접근이 올바르지 않다면 로그인 화면으로 보내버리기
        return redirect("user:login")
    
    post = Post.objects.get(id = id)

    review_form = ReviewForm()
    
    context = {
        "post": post,
        "review_form":review_form,
    }

    return render(request,"post/post_detail.html", context)

def post_detail_like(request, post_id):
    print("like start!")
    post = Post.objects.get(id = post_id)
    user = request.user

    print("post: ", post)
    print("user: ", user)

    # 유저가 찜한 목록에 이미 있다면 목록에서 지우고 없다면 목록에 추가
    user.like_posts.remove(post) if user.like_posts.filter(id = post.id).exists() else user.like_posts.add(post)

    return redirect("post:post_detail", id=post_id)

def my_list(request, post_id):
    my = Post.objects.get(id = post_id)
    user = request.user
# 사용자가 "좋아요를 누른 Post 목록"에 "좋아요 버튼을 누른 Post"가 존재한다면
    if user.like_posts.filter(id = my.id).exists():
       # My 목록에서 삭제
       user.like_posts.remove(my)

     # 존재하지 않는다면 My 목록에 추가
    else: 
        user.like_posts.add(my)
 # next로 값이 전달되었다면 해당 위치로, 전달되지 않았다면 피드페이지에서 해당 Post위치로 이동
    url_next = request.GET.get("next") or reverse("post:") + f"#post-{my.id}"

    return redirect(url_next)

def importExcel(request):
    if not request.user.is_authenticated: # 유저의 접근이 올바르지 않다면 로그인 화면으로 보내버려
        return redirect("user:login")

    if not request.user.is_staff: # 권한이 없는 유저가 접근할 경우
        return redirect("user:login")

    if request.method == 'POST':
        post_resource = PostResource()
        dataset = Dataset()
        new_post = request.FILES['my_file']
        imported_data = dataset.load(new_post.read(), format='xlsx')

        for data in imported_data:
            value = Post(
                content_name = data[0],
                content_description = data[1],
                content_act = data[2],
                content_dir = data[3],
                content_ott = data[4],
                content_genre = data[5],
                post_image = data[6],
                content_year = data[7]
            )
            value.save()

    return render(request, 'post/form.html')

templates/post/post_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>OMOA - {{ post.content_name }}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles3.css' %}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'post:ott_view' ott='all' %}">OMOA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{% url 'user:mypage' user.id %}">My Page</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">OTT</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Netflix' %}">Netflix</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Amazon' %}">Amazon</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Disney' %}">Disney</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='wavve' %}">wavve</a></li>
                        </ul>
                    <li class="nav-item"><a class="nav-link" href="{% url 'review:review_list' %}">Review</a></li>
                    </li>
                </ul>
                <form class="d-flex">
                    <a href="{% url 'user:logout' %}">Logout</a>
                </form>
            </div>
        </div>
    </nav>
    <!-- Product section-->
    <section class="py-5">
        <div class="row gx-4 gx-lg-5 align-items-center">

            <!-- Product section-->
            <section class="py-5">
                <div class="container px-4 px-lg-5 my-5">
                    <div class="row gx-4 gx-lg-5 align-items-center">
                        <div class="col-md-3"><img class="card-img-top mb-5 mb-md-0" src="{{ post.post_image }}"
                                alt="{{ post.content_name }}" /></div>
                        <div class="col-md-9">
                            <!-- <div class="small mb-1">SKU: BST-498</div> -->
                            <h1 class="display-5 fw-bolder">{{ post.content_name }}
                                <form action="{% url 'post:post_detail_like' post_id=post.id %}" method="POST"
                                    style="display:inline">
                                    {% csrf_token %}
                                    {% if user in post.like_user.all %}
                                    <button type="submit" style="border: none; background-color: transparent">
                                        ❤️
                                    </button>
                                    {% else %}
                                    <button type="submit" style="border: none; background-color: transparent">
                                        🤍
                                    </button>
                                    {% endif %}
                                </form>
                            </h1>
                            <div class="fs-5 mb-5">
                                <span>({{ post.content_year }})</span>
                            </div>
                            {% if post.content_genre %}
                            <div>
                                <div><strong>장르</strong></div>
                                <div>
                                    <p class="lead">{{ post.content_genre | cut:"None" }}</p>
                                </div>
                            </div>
                            {% endif %}
                            {% if post.content_dir %}
                            <div>
                                <div><strong>감독</strong></div>
                                <div>
                                    <p class="lead">{{ post.content_dir | cut:"None" }}</p>
                                </div>
                            </div>
                            {% endif %}
                            <br>
                            <div>
                                <div><strong>시놉시스</strong></div>
                                <div>{{ post.content_description | safe }}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Related items section-->
            <section class="py-5 bg-light">
                <div class="container px-4 px-lg-5 mt-5">
                    <h2 class="fw-bolder mb-4" style="display: inline;">Reviews </h2>

                    <a href="{% url 'review:review_add' post.id %}" class="btn btn-secondary" style="float: right;">review 쓰기</a>
                    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                        {% for r in post.review_set.all %}
                        <div class="card" style="width: 18rem; margin: 15px;">
                            <div class="card-body">
                                <h5 class="card-title">{{ r.user }}</h5>
                                <h6 class="card-subtitle mb-2 text-body-secondary">{{ r.title }}</h6>
                                <p class="card-text"> {{ r.content }}</p>
                            </div>
                            <a href="{% url 'review:review_detail' r.id %}" class="card-link btn btn-secondary" style="margin-bottom: 10px;">댓글 보기</a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
            <!-- Footer-->
            <footer class="bg-dark">
                <div class="container">
                    <p class="m-0 text-center text-white">Copyright &copy; OMOA 2025</p>
                </div>
            </footer>
            <!-- Bootstrap core JS-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Core theme JS-->
            <script src="js/listscripts.js"></script>
        </div>

    </section>
</body>

</html>

templates/post/post_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>OMOA-List</title>
    <title>Netflix</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles3.css' %}" rel="stylesheet" />

<style>
.radius_img_2 {
    border-radius: 20%;
}
</style>
</head>

<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'post:ott_view' ott='all' %}">OMOA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'user:mypage' user.id %}">My Page</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">OTT</a>
                              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                  <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Netflix' %}">Netflix</a></li>
                                  <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Amazon' %}">Amazon</a></li>
                                  <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Disney' %}">Disney</a></li>
                                  <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='wavve' %}">wavve</a></li>
                              </ul>
                        <li class="nav-item"><a class="nav-link"href="{% url 'review:review_list' %}">Review</a></li>
                        </li>
                    </ul>
                    <form class="d-flex" role="search" method="GET">
                        <input class="form-control me-2" type="search" placeholder="작품명으로my 검색" aria-label="Search" name="q" />
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <div class="d-flex justify-content-around">
                    {% if ott == 'Netflix' %}
                        <img src="https://images.justwatch.com/icon/207360008/s100/netflix.avif" class="radius_img_2">
                    {% elif ott == 'Amazon' %}
                        <img src="https://images.justwatch.com/icon/322992749/s100/amazonprimevideo.avif" class="radius_img_2">
                    {% elif ott == 'Disney' %}
                        <img src="https://images.justwatch.com/icon/313118777/s100/disneyplus.avif" class="radius_img_2">
                    {% elif ott == 'wavve' %}
                        <img src="https://images.justwatch.com/icon/155655742/s100/wavve.avif" class="radius_img_2">
                    {% endif %}

                </div>
                <h1 class="display-4 fw-bolder">OMOA</h1>
                <p class="lead fw-normal text-white-50 mb-0">OTT의 모든 것을 담다</p>
            </div>
        </div>
    </header>
        <!-- Section-->
        <section class="bg-dark py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for post in posts %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ post.post_image }}" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ post.content_name }}</h5>
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'post:post_detail' post.id %}">click</a></div>
                            </div>
                        </div>
                    </div>
                  {% endfor %}
                </div>
            </div>
        </section>
</body>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</html>