omoa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("post/", include("post.urls")),
    path("review/", include("review.urls")),
    path("", include("ranking.urls")),
]
urlpatterns += static(
    prefix= settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT,
)

post/urls.py
from django.urls import path
from post import views

app_name = "post"
urlpatterns = [
    path("ott/<str:ott>/", views.ott_view, name= "ott_view"),
    path("post_detail/<int:id>/", views.post_detail, name= "post_detail"),
    path("post_detail/<int:post_id>/like/", views.post_detail_like, name= "post_detail_like"),
    path("import/", views.importExcel, name= "importExcel"),
]

ranking/urls.py
from django.urls import path
from ranking import views

app_name = "ranking"
urlpatterns = [
    path("",views.omoa_home, name = "home"),
    path("ranking/",views.ranking_page, name = "ranking"),
]

review/urls.py
from django.urls import path
from review import views

app_name = "review"
urlpatterns = [
    path("",views.review_list, name = "review_list"),
    path("add/<int:post_id>/",views.review_add, name = "review_add"),
    path("delete/<int:review_id>/",views.review_delete, name = "review_delete"),
    path("<int:review_id>/",views.review_detail, name= "review_detail"),
    path("comment_add/", views.comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", views.comment_delete, name="comment_delete"),
]

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from user import views

app_name = "user"
urlpatterns = [
    path("login/", views.login_view, name = "login"),
    path("logout/", views.logout_view, name = "logout"),
    path("signup/", views.signup, name = "signup"),
    path("my_page/<int:id>/", views.my_page, name = "mypage"),
    path("my_page/<int:id>/follow/", views.user_follow, name = "userfollow"),
    path("my_page/<int:id>/mylike/", views.my_likelist, name= "mylike"),
    path("my_page/<int:id>/myreview/", views.my_reviewlist, name= "myreview"),
    path("my_page/<int:id>/myfollow/", views.my_followlist, name= "myfollow"),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

review/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    user = models.ForeignKey("user.User",
                             verbose_name = "작성자",
                             on_delete = models.CASCADE)
    post = models.ForeignKey("post.Post",
                             verbose_name="작품명",
                             on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add = True)
    title = models.CharField("제목")

    def __str__(self):
        return f"{self.user.id}의 게시글(id: {self.id})"
    

class Comment(models.Model):
    user = models.ForeignKey("user.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    review = models.ForeignKey("review.Review", verbose_name = "게시글", on_delete = models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add= True)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    profile_image = models.ImageField("프로필 이미지", 
                                      upload_to="user/profile", 
                                      blank=True)
    short_description = models.TextField("소개글", blank=True)
    
    like_posts = models.ManyToManyField(
        "post.Post",
        verbose_name="좋아요 누른 Post 목록",
        related_name = "like_user",
        blank = True,
    )
    following = models.ManyToManyField(
        "self",
        verbose_name = "팔로우 중인 사용자들",
        related_name = "follower",
        symmetrical = False,
        through = "user.Relationship",
    )

    def __str__(self):
        return self.username
    
class Relationship(models.Model):
    from_user = models.ForeignKey(
        "user.User",
        verbose_name = "팔로우를 요청한 사용자",
        related_name = "following_relationships",
        on_delete = models.CASCADE,
    )
    to_user = models.ForeignKey(
        "user.User",
        verbose_name = "팔로우 요청의 대상",
        related_name = "follower_relationships",
        on_delete = models.CASCADE,
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"관계 ({self.from_user} -> {self.to_user})"


    

user/forms.py
from django import forms
from django.core.exceptions import ValidationError
from user.models import User

class LoginForm(forms.Form):
    username = forms.CharField(
        min_length=5,
        widget = forms.TextInput(
            attrs = {"placeholder": "5자리 이상 입력", "class":"input", "id":"user_name"},
        )
        )
    password = forms.CharField(
        min_length=8,
        widget = forms.PasswordInput(
            attrs={"placeholder": "8자리 이상 입력", "class":"input", "id":"user_pass"},
        )
        )
    
class SignupForm(forms.Form):
    username = forms.CharField(
        min_length=5,
        widget = forms.TextInput(
            attrs = {"placeholder": "5자리 이상 입력", "class":"input", "id":"user_name"},
        )
    )
    password1 = forms.CharField(
        min_length=8,
        widget = forms.PasswordInput(
            attrs={"placeholder": "8자리 이상 입력", "class":"input", "id":"user_pass"},
        )
        )
    password2 = forms.CharField(
        min_length=8,
        widget = forms.PasswordInput(
            attrs={"placeholder": "8자리 이상 입력", "class":"input", "id":"user_pass2"},
        )
        )
    profile_image = forms.ImageField()
    short_description = forms.CharField(
        widget = forms.TextInput(
            attrs = {"class":"input"}
        )
    )

    def clean_username(self):
        username = self.cleaned_data["username"]

        if User.objects.filter(username = username).exists():
            raise ValidationError(f"입력한 사용자명({username})은 이미 사용 중입니다")
        
        return username
    
    def clean(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 != password2:
            # password2 필드에 오류를 추가
            self.add_error("password2", "비밀번호와 비밀번호 확인란의 값이 다릅니다")

    def save(self):
        username = self.cleaned_data["username"]
        password1 = self.cleaned_data["password1"]
        profile_image = self.cleaned_data["profile_image"]
        short_description = self.cleaned_data["short_description"]
        
        # 에러가 없다면, 사용자를 생성하고 로그인 처리 후 피드 페이지로 이동
        user = User.objects.create_user(
            username = username,
            password = password1,
            profile_image = profile_image,
            short_description = short_description,
        )
        return user

user/views.py
from django.shortcuts import render, redirect, get_object_or_404
from user.forms import LoginForm, SignupForm
from django.contrib.auth import authenticate, login, logout
from user.models import User
from django.urls import reverse



# Create your views here.
def login_view(request):
    # 이미 로그인되어 있다면
    if request.user.is_authenticated:
        return redirect('post:ott_view', "all")
    
    if request.method == "POST":
        # LoginForm 객체를 만들며, 입력 데이터는 request.POST 를 사용
        form = LoginForm(data = request.POST)

        # LoginForm 에 전달된 데이터가 유효하다면
        if form.is_valid():
            # username과 password 값을 가져와 변수에 할당
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # username, password에 해당하는 사용자가 있는지 검사
            user = authenticate(username = username, password = password)

            # 해당 사용자가 존재한다면
            if user:
                # 로그인 처리 후, 피드 페이지로 redirect
                login(request, user)
                return redirect('post:ott_view', "all")
            
            else:
                # 사용자가 없다면 form에 에러 추가
                form.add_error(None, "입력한 자격증명에 해당하는 사용자가 없습니다")

    else:
        # LoginForm 객체를 생성
        form = LoginForm()

    # 생성한 LoginForm 객체를 템플릿에 "form" 이라는 키로 전달
    context = {
        "form": form,
    }
    return render(request, "user/login.html", context)

def logout_view(request):
    # logout 함수 호출에 request를 전달
    logout(request)

    # logout 처리 후, 로그인 페이지로 이동
    return redirect("user:login")

def signup(request):
    if request.method == "POST":
        form = SignupForm(data = request.POST, files = request.FILES)

        if form.is_valid():
            # Form에 에러가 없다면 form의 save() 메서드로 사용자를 생성
            user = form.save()
            login(request, user)
            return redirect('post:ott_view', "all")

    else: # GET 요청에서는 빈 form 을 보여줌
        # SignupForm 인스턴스를 생성, Template에 전달
        form = SignupForm()

    # context로 전달되는 form은 두 가지 경우가 존재
    # 1. POST 요청에서 생성된 form 이 유효하지 않은 경우 -> 에러를 포함한 form이 사용자에게 보여짐
    # 2. GET 요청으로 빈 form 이 생성된 경우 -> 빈 form이 사용자에게 보여짐
    context = {
        "form": form
    }
    return render(request, "user/signup.html", context)

def followers(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.follower_relationships.all()
    context = {
        "user":user,
        "title":"Followers",
        "relationships":relationships,
    }
    return render(request,"user/followers.html", context)

def following(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.following_relationships.all()
    context = {
        "user":user,
        "title":"Following",
        "relationships":relationships,
    }
    return render(request,"user/following.html", context)

def follow(request, user_id):
    # 로그인한 유저
    user = request.user

    # 팔로우 하려는 유저
    target_user = get_object_or_404(User, id= user_id)

    # 팔로우 하려는 유저가 이미 자신의 팔로잉 목록에 있는 경우
    if target_user in user.following.all():
        # 팔로잉 목록에서 제거
        user.following.remove(target_user)
    # 팔로우 하려는 유저가 자신의 팔로잉 목록에 없는 경우
    else:
        # 팔로잉 목록에 추가
        user.following.add(target_user)
    
    # 팔로우 토글 후 이동할 URL이 전달되었다면 해당 주소로,
    # 전달되지 않았다면 로그인 한 유저의 프로필 페이지로 이동
    url_next = request.GET.get("next") or reverse("user:profile", args=[user.id])
    return redirect(url_next)

def my_page(request, id):

    print("mypage불러오기")
    if not request.user.is_authenticated: # 유저의 접근이 올바르지 않다면 로그인 화면으로 보내버리기
        return redirect("user:login")
    

    pageuser = User.objects.get(id = id)
    context = {"pageuser": pageuser}

    return render(request, "user/profile.html", context)

def user_follow(request, id):
    print("follow start!")
    follow_user = User.objects.get(id = id)
    user = request.user

    # 유저가 찜한 목록에 이미 있다면 목록에서 지우고 없다면 목록에 추가
    # user.like_posts.remove(post) if user.like_posts.filter(id = post.id).exists() else user.like_posts.add(post)
    user.following.remove(follow_user) if follow_user in user.following.all() else user.following.add(follow_user)

    return redirect("user:mypage", id=id)

def my_likelist(request, id):
    user = User.objects.get(id = id)
    me = request.user
    context = {
        "user": user,
        "me": me,
        }

    return render(request, "user/mylike.html", context)

def my_reviewlist(request, id):
    user = User.objects.get(id = id)

    context = {"user": user}

    return render(request, "user/myreview.html", context)

def my_followlist(request, id):
    user = User.objects.get(id = id)

    context = {"user": user}

    return render(request, "user/myfollow.html", context)

templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>OMOA-SignIn</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="{% static 'css/login.css' %}" rel="stylesheet" />
    <script src="{% static 'js/login.js' %}"></script>
</head>

<body>
    <!-- LOGIN MODULE -->
    <div class="login">
        <div class="wrap">
            <div class="content">
                <!-- LOGO -->
                <div class="logo">
                    <!-- <img src="http://res.cloudinary.com/dpcloudinary/image/upload/v1506186248/logo.png" alt=""> -->
                    <!-- <img src="https://cafeptthumb-phinf.pstatic.net/MjAyNTEwMDFfMjk0/MDAxNzU5MzAxMDc2NTc2.lEg46iffTdX96NztE6pkPuGpgkFPqGDquLScICq73ZMg.uEYQS9RzfRZ7555d3R5gC75xMVUS8FZrR_fr9grQ8eMg.PNG/3.png?type=w1600" alt=""> -->
                </div>
                <div id="slideshow">
                    <div class="one">
                        <h2><span>OMOA</span></h2>
                        <p>OTT의 모든 것을 담다</p>
                    </div>
                </div>
            </div>
            <!-- LOGIN FORM -->
            <div class="user">
                <div class="form-wrap">
                    <!-- TABS -->
                    <!-- TABS CONTENT -->
                    <div class="tabs-content">
                        <!-- TABS CONTENT LOGIN -->
                        <div id="login-tab-content" class="active">
                            <form class="login-form" action="" method="POST">
                                {% csrf_token %}
                                {{ form }}
                                <input type="submit" class="button" value="Login">
                            </form>
                            <div class="help-action">
                                <p><a class="forgot" href="{% url 'user:signup' %}">Sign Up</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/user/mylike.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>{{ user.username}}의 찜한목록</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon2.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/liststyles.css' %}" rel="stylesheet" />

<style>
    .background {
        background-image: url("{{ review.post.post_image }}"); 
        background-size: contain; 
        background-repeat: no-repeat; 
        background-position: center; 
}
</style>
</head>
    <body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'post:ott_view' ott='all' %}">OMOA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'user:mypage' user.id %}">My Page</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">OTT</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Netflix' %}">Netflix</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Amazon' %}">Amazon</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Disney' %}">Disney</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='wavve' %}">wavve</a></li>
                        </ul>
                <li class="nav-item"><a class="nav-link"href="{% url 'review:review_list' %}">Review</a></li>
                </li>
            </ul>
            <form class="d-flex">
                <a href="{% url 'user:logout' %}">Logout</a>
            </form>
        </div>
    </div>
</nav>
    <main class="flex-shrink-0">
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 align-items-center justify-content-center">
                    <div class="col-lg-8 col-xl-7 col-xxl-6">
                        <div class="my-5 text-center text-xl-start">
                            <h1 class="display-5 fw-bolder text-white mb-2">{{ user.username }}
                            </h1>
                            <p class="lead fw-normal text-white-50 mb-4">{{ user.short_description }}</p>
                        </div>
                    </div>
                    <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center">
                        {% if user.profile_image %}
                        <img src="{{ user.profile_image.url }}" width="300">
                        {% else %}
                        <img src="https://dummyimage.com/600x350/ced4da/6c757d" alt="..." />
                        {% endif %}
                    </div>
                </div>
            </div>
        </header>
        <!-- Features section-->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <h2 class="fw-bolder mb-0">찜 목록 {{ user.like_posts.all.count }}개</h2>
                    {% for post in user.like_posts.all %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">{{ post.content_ott | cut:", Netflix Standard with Ads" }}</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ post.post_image }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ post.content_name }}</h5>
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'post:post_detail' post.id %}">click</a></div>
                            </div>
                        </div>
                    </div>
                  {% endfor %}
                </div>
            </div>
        </section>
    </main>
    <!-- Footer-->
    <footer class="bg-dark py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto">
                    <div class="small m-0 text-white"><p class="m-0 text-center text-white">Copyright &copy; OMOA 2025</p></div>
                </div>
                <div class="col-auto">
                    <a class="link-light small" href="#!">Privacy</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">Terms</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">Contact</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/profile_scripts.js' %}"></script>
</body>

templates/user/myreview.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>{{ user.username}}의 리뷰목록</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon2.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/liststyles.css' %}" rel="stylesheet" />

<style>
    .background {
        background-image: url("{{ review.post.post_image }}"); 
        background-size: contain; 
        background-repeat: no-repeat; 
        background-position: center; 
}
</style>
</head>
    <body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'post:ott_view' ott='all' %}">OMOA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'user:mypage' user.id %}">My Page</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">OTT</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Netflix' %}">Netflix</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Amazon' %}">Amazon</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Disney' %}">Disney</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='wavve' %}">wavve</a></li>
                        </ul>
                <li class="nav-item"><a class="nav-link"href="{% url 'review:review_list' %}">Review</a></li>
                </li>
            </ul>
            <form class="d-flex">
                <a href="{% url 'user:logout' %}">Logout</a>
            </form>
        </div>
    </div>
</nav>
    <main class="flex-shrink-0">
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 align-items-center justify-content-center">
                    <div class="col-lg-8 col-xl-7 col-xxl-6">
                        <div class="my-5 text-center text-xl-start">
                            <h1 class="display-5 fw-bolder text-white mb-2">{{ user.username }}
                            </h1>
                            <p class="lead fw-normal text-white-50 mb-4">{{ user.short_description }}</p>
                        </div>
                    </div>
                    <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center">
                        {% if user.profile_image %}
                        <img src="{{ user.profile_image.url }}" width="300">
                        {% else %}
                        <img src="https://dummyimage.com/600x350/ced4da/6c757d" alt="..." />
                        {% endif %}
                    </div>
                </div>
            </div>
        </header>
    <!-- review section -->
        <section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <h2 class="fw-bolder mb-0">{{ user.username }}님의 리뷰, 총 {{ user.review_set.all.count }}건</h2>
                    {% for review in user.review_set.all %}
                        <div class="col mb-5">
                            <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">{{ review.post.content_ott | cut:", Netflix Standard with Ads" }}</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ review.post.post_image }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ review.post.content_name }}</h5>
                                    <!-- Product price-->
                                    <span class="text-muted">{{ review.title }}</span>
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'review:review_detail' review.id %}">click</a></div>
                            </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
    <!-- Footer-->
    <footer class="bg-dark py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto">
                    <div class="small m-0 text-white"><p class="m-0 text-center text-white">Copyright &copy; OMOA 2025</p></div>
                </div>
                <div class="col-auto">
                    <a class="link-light small" href="#!">Privacy</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">Terms</a>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="#!">Contact</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/profile_scripts.js' %}"></script>
</body>

templates/user/nav.html
<nav>
    <h1>
        <a href="{% url 'post:choice' %}">OMOA</a>
    </h1>   
    <a href="{% url 'user:logout' %}">Logout</a>
</nav>

templates/user/nav.search.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'post:ott_view' ott='all' %}">OMOA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'user:mypage' user.id %}">My Page</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'ranking:ranking' %}">Ranking</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">OTT</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Netflix' %}">Netflix</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Amazon' %}">Amazon</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='Disney' %}">Disney</a></li>
                            <li><a class="dropdown-item" href="{% url 'post:ott_view' ott='wavve' %}">wavve</a></li>
                        </ul>
                <li class="nav-item"><a class="nav-link"href="{% url 'review:review_list' %}">Review</a></li>
                </li>
            </ul>
            <form class="d-flex" role="search" method="GET">
                <input class="form-control me-2" type="search" placeholder="작품명,게시물 제목으로 검색" aria-label="Search" name="q" />
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>